pipeline {
    agent { label 'jenkins-agent' }   

    environment {
        DOCKERHUB_USER = 'jhamadhav2025'
        IMAGE_NAME     = 'banking-app'
    }

    stages {
        stage('SCM Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Maven Build') {
            steps {
                sh './mvnw clean package'
            }
        }

        stage('Docker Build & Push') {
            steps {
                sh """
                  docker build -t ${DOCKERHUB_USER}/${IMAGE_NAME}:${BUILD_NUMBER} .
                  echo "${DOCKERHUB_PASS}" | docker login -u "${DOCKERHUB_USER}" 
                  docker push ${DOCKERHUB_USER}/${IMAGE_NAME}:${BUILD_NUMBER}
                """
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh """
                ssh -o StrictHostKeyChecking=no ubuntu@<15.206.139.185> '
                  kubectl set image deployment/banking-app \
                    banking-app=${DOCKERHUB_USER}/${IMAGE_NAME}:${BUILD_NUMBER} \
                    --namespace=default || \
                  kubectl apply -f /home/ubuntu/manifests/banking-app.yaml
                '
                """
            }
        }
    }
}
