
pipeline {
    agent { label 'banking-agent' }

    triggers {
        githubPush()  
    }

    stages {

        stage('Checkout Code') {
            steps {
                echo "Pulling latest code..."
                git branch: 'main',
                    url: 'https://github.com/madhav-jha/banking-app-devops.git'
            }
        }

        stage('Build') {
            steps {
                echo "Running Maven build"
                dir('app') {
                    sh 'mvn clean package'
                }
            }
        }
        
        stage('Docker Build & Push') {
    steps {
        dir('app') {
            script {
                image = docker.build("jhamadhav2025/banking-app:${BUILD_NUMBER}")
                docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-creds') {
                    image.push()
                }
            }
        }
    }
}


        stage('Tests') {
            steps {
                echo "Running tests..."
                dir('app') {
                    sh 'mvn test'
                }
            }
        }

        stage('Archive Artifact') {
            steps {
                echo "Archiving JAR..."
                archiveArtifacts artifacts: 'app/target/*.jar', fingerprint: true
            }
        }
    }

    post {
        success {
            emailext(
                to: "jhmadhav2025@gmail.com",
                subject: "SUCCESS: ${JOB_NAME} #${BUILD_NUMBER}",
                body: "Build successful. Logs: ${BUILD_URL}console"
            )
        }
        failure {
            emailext(
                to: "jhamadhav2025@gmail.com",
                subject: "FAILED: ${JOB_NAME} #${BUILD_NUMBER}",
                body: "Build failed. Check logs: ${BUILD_URL}console"
            )
        }
    }
}
