apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app
  labels:
    app: banking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
    spec:
      containers:
      - name: banking-app
        image: jhamadhav2025/banking-app:3.0
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: banking-app-service
spec:
  type: NodePort
  selector:
    app: banking-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30082
